name: notion_template_connector
description: "Notion Template Connector は、Flutter アプリからあなたの Notion アカウントに対して、開発者提供のテンプレート連携（OAuth 認証）を実装するサンプルプロジェクトです。"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.5
  flutter_secure_storage: ^9.2.4
  flutter_riverpod: ^2.6.1
  http: ^1.3.0
  envied: ^1.1.0
  uni_links: ^0.5.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  envied_generator: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - .env